### ISSUE TITLE
Allow complex regular expressions with Naming Conversion

### ISSUE THREAD

**Issue by ChenCMD** [SPYGlassMC/datapack-language-server#770]
Currently it is not possible to use "." And "+" when Naming Convention is set.

If this issue is accepted, please assign me.
Create a PR.

**Comment by NeunEinser** [comment]
Colons are also not accepted, which effects a utility namespace of mine, where I save different time formats to storage using keys like "hh:mm:ss" to illustrate the format of the value.

**Comment by ChenCMD** [comment]
Naming Conversion applies only to team, tag, nbtkey, objective, the characters allowed in these should be a-zA-Z._ +-

**Comment by SPGoding** [comment]
How about expanding the format of `NamingConvention` to support either a default template (`camelCase`, `snake_case`, whatever), a regular expression (a JSON string enclosed by slashes `/`, e.g. `"/\\d\\d:\\d\\d:\\d\\d/"`), or a complex object?

e.g. To allow [an NBT key like `hh:mm:ss`](https://github.com/SPGoding/datapack-language-server/issues/770#issuecomment-734929101):
```jsonc
"namingOfNbtKey": "/\\d\\d:\\d\\d:\\d\\d/"
```

To allow a score holder (fake player) name like `$foo_bar`:
```jsonc
"namingOfScoreHolder": {
	"prefix": "$",
	"words": ["lowercase"],
	"sep": ["_"]
}
```

To allow an objective name like `namespace.camelCaseName`:
```jsonc
"namingOfObjective": {
	"words": ["lowercase", "lowercase", "Camel"], // The first two words should be all lowercased, other words should be Camel style.
	"sep": [".", ""] // The first two words are separated by a dot (.), other words shouldn't be separated by any symbols.
}
```
