### ISSUE TITLE
VSCode thinks the setting datapack.lint.nameOfScoreHolders is called without the f in "Of"

### ISSUE THREAD

**Issue by NeunEinser** [SPYGlassMC/datapack-language-server#777]
AUto complete in settings.json yields `datapack.lint.nameOScoreHolders` isntead of `datapack.lint.nameOfScoreHolders`

**Comment by ChenCMD** [comment]
Fixed https://github.com/SPYGlassMC/vscode-datapack-helper-plus/commit/34222d23b01447600da7f46469c76fa49a36147d
