### ISSUE TITLE
Score_holder naming violation uses string that claims "objective" is wrong

### ISSUE THREAD

**Issue by NeunEinser** [SPYGlassMC/datapack-language-server#778]
![grafik](https://user-images.githubusercontent.com/12124394/100545181-f55eac80-325a-11eb-9d70-562881188b64.png)

**Comment by ChenCMD** [comment]
Fix https://github.com/SPYGlassMC/datapack-language-server/commit/0ce9f17c4063ba269b2708db708372c0fa5698b7
